# Spring Boot application configuration

# Server configuration
server:
  port: 8080

# Database configuration
spring:
  kafka:
    bootstrap-servers: localhost:9092  # Kafka Server
    consumer:
      group-id: my-consumer-group  # Gruppo di consumatori
      auto-offset-reset: earliest   # Inizia a leggere dall'inizio del topic
    listener:
      missing-topics-fatal: false   # Gestisce l'assenza di topic
      value-deserializer: org.springframework.kafka.core.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:mysql://localhost:3306/lavanderia_anagrafica
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Logging configuration
logging:
  level:
    root: INFO
    com.example: DEBUG

# Custom application properties
custom:
  app:
    name: Lavanderia Maione
    version: 1.0
    description: Gestionale della lavanderia Maione
