# Spring Boot application configuration

# Server configuration
server:
  port: 8080

# Database configuration
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/lavanderia
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Logging configuration
logging:
  level:
    root: INFO
    com.example: DEBUG

# Custom application properties
custom:
  app:
    name: Lavanderia Maione
    version: 1.0
    description: Gestionale della lavanderia Maione
